version: "3.8"
services:
  app:
    container_name:
      banking-web
    image: banking-web
    build:
      dockerfile: ./.build/Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    container_name:
      banking-db
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: